import type { KBArticle, Tutorial } from "./types";

const DEMO_VIDEO = "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4";

export const KB_ARTICLES: KBArticle[] = [
  {
    id: "kb-1",
    title: "Getting started with the DDDP Portal Hub",
    excerpt: "How to choose the right portal and what each destination offers.",
    category: "Getting Started",
    tags: ["portal", "navigation", "overview", "hub"],
    type: "guide",
    body: "The Portal Hub connects you to the DDDP Frontend, Backend, and Public Portal. Select the card that matches your role. Each link opens in a new tab so you can return to the hub at any time.\n\nUse the Help Desk Knowledge Hub for manuals, how-to tutorials, and the AI assistant when you need guided answers.",
  },
  {
    id: "kb-2",
    title: "Accessing district development data",
    excerpt: "Where to find official district-level datasets and reports.",
    category: "Data Access",
    tags: ["data", "districts", "reports"],
    type: "article",
    body: "Use the DDDP Frontend for interactive dashboards. The Public Portal publishes datasets intended for citizens and partners. Authorised staff should use the Backend for data management tasks.\n\nAt national level, open APR Dashboard or DPAT Dashboard after selecting Ghana to review yearly summary reports.",
  },
  {
    id: "kb-3",
    title: "User account and permissions FAQ",
    excerpt: "Common questions about roles, login, and access requests.",
    category: "FAQ",
    tags: ["accounts", "permissions", "faq", "login"],
    type: "faq",
    body: "Q: Who can access the Backend?\nA: Only authorised MLGRD and partner administrators.\n\nQ: Do I need an account for the Public Portal?\nA: Many resources are open; some reports may require registration.\n\nQ: Where do I sign in?\nA: Open www.dddp.gov.gh, click Sign-In, and enter your valid username and password.\n\nQ: I forgot my password — what do I do?\nA: On the login page click Forgot Password, enter your username, click Recover, then follow the email link to set a new password and click Restore.",
  },
  {
    id: "kb-4",
    title: "DDDP Frontend user manual",
    excerpt: "Navigation, dashboards, exports, and performance workflows.",
    category: "Manuals",
    tags: ["frontend", "manual", "dashboard", "navigation"],
    type: "manual",
    body: "After signing in to the DDDP New Frontend:\n\n1. Choose a Region from the left side menu to open the Dashboard.\n2. Use the top menu for Performance Setup, RCC Progress Report, Performance Contract Regional, Trackers, and related tools.\n3. District pages include Performance Monitoring for year/quarter assessments.\n4. National views (country = Ghana) include APR Dashboard, DPAT Dashboard, and Consolidated Performance Contract Assessment.\n\nExport tables via the download icon where available. Bookmark frequent views from the star menu when enabled for your role.",
  },
  {
    id: "kb-5",
    title: "Submitting a support request",
    excerpt: "How to open tickets and what information to include.",
    category: "Support",
    tags: ["tickets", "support"],
    type: "guide",
    body: "Open Help Desk → Tickets, describe the issue clearly, and pick a category. Include screenshots or error messages when possible. You will receive in-app notifications when status changes.\n\nFor training questions, browse the Learning Center tutorials first — many DDDP/DPAT steps are documented there.",
  },
  {
    id: "kb-6",
    title: "Data quality and validation",
    excerpt: "Understanding validation rules and correction workflows.",
    category: "Data Access",
    tags: ["validation", "quality"],
    type: "article",
    body: "The platform applies validation rules before publishing district indicators. Backend users can review flagged records and approve corrections through the validation queue.\n\nWhen completing Performance Monitoring, provide an Assessment Summary covering strengths, weaknesses, and technical backstopping needs before you click Complete Assessment.",
  },
  {
    id: "kb-7",
    title: "Logging into DDDP New Frontend",
    excerpt: "Sign-in steps for the DDDP web application.",
    category: "Getting Started",
    tags: ["login", "signin", "frontend", "password"],
    type: "guide",
    body: "To log into DDDP New Frontend:\n\na. Open a web browser (Chrome, Firefox, or Microsoft Edge).\nb. Enter the DDDP URL in the address bar and press Enter (www.dddp.gov.gh for the standard portal).\nc. Enter your valid username and password.\nd. Click Sign In.\n\nYou land on the Dashboard (or Tracker Capture, depending on the interface you open).",
  },
  {
    id: "kb-8",
    title: "Forgot password recovery",
    excerpt: "Reset your DDDP password using account recovery email.",
    category: "FAQ",
    tags: ["password", "recovery", "forgot", "login"],
    type: "faq",
    body: "Q: How do I reset a forgotten password?\nA:\n1. Go to www.dddp.gov.gh and open the login page.\n2. Click Forgot Password.\n3. Enter your Username and click Recover.\n4. Check your email for the account recovery link.\n5. Open the link, enter a new password, confirm it, and click Restore.\n\nIf you do not receive the email, contact support via a Help Desk ticket under Account & access.",
  },
  {
    id: "kb-9",
    title: "Performance Setup (Region, Year, Quarter)",
    excerpt: "Configure indicators for a selected region before monitoring.",
    category: "Performance",
    tags: ["performance", "setup", "indicators", "region", "quarter"],
    type: "guide",
    body: "Performance Setup prepares the indicators used for regional and district assessments.\n\nSteps:\na. Select a Region from the left side menu.\nb. On the top menu, click Performance Setup.\nc. Select the Year and Quarter, then scroll down and select one or more Indicators for that region.\nd. Click Save Performance Setup.\n\nComplete this before running Monitoring Assessment or Performance Monitoring for the same period.",
  },
  {
    id: "kb-10",
    title: "RCC monitoring indicators overview",
    excerpt: "Set up RCC indicators and run regional monitoring assessments.",
    category: "RCC",
    tags: ["rcc", "indicators", "monitoring", "assessment"],
    type: "article",
    body: "Regional Coordinating Council (RCC) monitoring in DDDP has two main parts: Indicator Setup and Monitoring Assessment.\n\nSet up indicators:\na. Click Setup Mode below the left menu pane.\nb. In RCC Indicator Setup, click +Add Indicator (top right) and create the indicator.\n\nMonitoring assessment:\nc. Select a Region, open Performance Setup, choose Year/Quarter and indicators, then Save Performance Setup.\nd. On the district page, open the Performance Monitoring tab.\ne. Select Year and Quarter, then click Load Assessment.\nf. Use Consolidated Monitoring at regional level — select Year and Target Quarter, then Load Assessment.",
  },
  {
    id: "kb-11",
    title: "Annual Progress Report (RCC Progress Report)",
    excerpt: "Build and save the RCC Annual Progress Report.",
    category: "Reports",
    tags: ["apr", "progress", "report", "rcc", "annual"],
    type: "manual",
    body: "To prepare an Annual Progress Report via RCC Progress Report:\n\na. Select a Region from the left menu.\nb. On the top menu, click RCC Progress Report.\nc. Select Year and Period so tables populate automatically.\nd. Click Start RCC Progress Report.\ne. Provide the Executive Summary and General Information, then save both.\n\nFor the national APR Dashboard, select Ghana, open APR Dashboard from the top menu, choose a Year, and scroll to view the country summary.",
  },
  {
    id: "kb-12",
    title: "Performance Contract (Regional and District)",
    excerpt: "Load and complete OHLGS performance contract assessments.",
    category: "Performance",
    tags: ["performance", "contract", "ohlgs", "regional", "district"],
    type: "guide",
    body: "Performance Contract Regional:\na. Select a region from the side menu.\nb. Click Performance Contract Regional on the top menu.\nc. Select a Year and click Load Assessment to load the OHLGS assessment record.\nd. Review the assessment, then click Complete Assessment when done.\n\nThe same process applies at district level.\n\nNational consolidated view: select the country, open Consolidated Performance Contract, choose year and region, then click Load Consolidated.",
  },
  {
    id: "kb-13",
    title: "Performance Monitoring (Year and Quarter)",
    excerpt: "Run district performance monitoring and assessment summaries.",
    category: "Performance",
    tags: ["performance", "monitoring", "assessment", "summary"],
    type: "guide",
    body: "a. Select a Region from the left menu.\nb. On the selected district page, open the Performance Monitoring tab.\nc. Click Start Assessment (top right) to populate district data, then click Save Indicator.\nd. Scroll to Assessment Summary — document strengths, weaknesses, and technical backstopping required — then Save Assessment Summary.\ne. Scroll up and click Complete Assessment to confirm.",
  },
  {
    id: "kb-14",
    title: "Trackers overview — find, register, and bulk load",
    excerpt: "Identify trackers, register records, and upload bulk data.",
    category: "Trackers",
    tags: ["trackers", "register", "bulk", "timeline"],
    type: "manual",
    body: "Find trackers:\na. Select a Region from the left menu.\nb. Click Trackers on the top menu.\nc. Use the search box to view and select trackers.\n\nRegister a tracker:\na–b. Open Trackers as above.\nc. Click Register.\nd. Fill in details, then Save and Continue, Save and Add New, or Close.\n\nBulk load:\na. Select a District from the left menu.\nb. Open Trackers → Bulk load.\nc. Download Template, populate it, and upload.\n\nTimeline: open a registered record → Timeline to view details; use New Event to add timeline entries.\nRelationships: open a record → Relationship → Add Relationship → fill details → Register Relationship.",
  },
  {
    id: "kb-15",
    title: "DPAT and APR national dashboards",
    excerpt: "View national DPAT and APR summary reports for Ghana.",
    category: "Reports",
    tags: ["dpat", "apr", "dashboard", "national", "ghana"],
    type: "article",
    body: "Both dashboards are used at national level.\n\nAPR Dashboard:\na. Select Ghana.\nb. Click APR Dashboard on the top menu.\nc. Select a Year and scroll to view the country summary report.\n\nDPAT Dashboard:\na. Select Ghana.\nb. Click DPAT Dashboard on the top menu.\nc. Select a Year and scroll to view the DPAT summary report for Ghana.",
  },
  {
    id: "kb-16",
    title: "Tracker Capture interface FAQ",
    excerpt: "Organisational units, program lists, and register actions explained.",
    category: "FAQ",
    tags: ["tracker", "capture", "register", "faq"],
    type: "faq",
    body: "Q: What is the Organisational Units pane?\nA: It shows the district (organisation unit) you are operating in.\n\nQ: What is the Tracker Capture dropdown?\nA: It lists available tracker programs (Meeting, Annual Action Plan, Bill Tracker, and more).\n\nQ: What do List / Search / Register tabs do?\nA: They let you list existing records, search, or capture new registrations.\n\nQ: What happens after I fill a registration form?\nA: You can Save and continue (go to the tracker page), Save and add new (clear the form for another entry), Print form, or Cancel.",
  },
  {
    id: "kb-17",
    title: "Registering programs in Tracker Capture",
    excerpt: "Meetings, Annual Action Plans, Bill Tracker, and other programs.",
    category: "Trackers",
    tags: ["tracker", "meeting", "aap", "bill", "boundary", "capacity", "community"],
    type: "manual",
    body: "Common registration flow for Tracker Capture programs:\n\n1. Open the Tracker Capture dropdown and select the program (e.g. Meeting, Annual Action Plan, Bill Tracker, Boundary Dispute Tracker, Capacity Building Needs Tracker, Community Profile Tracker, Computerized System Tracker, Decisions and Complaints Tracker).\n2. Select Register.\n3. Complete the required form fields.\n4. Choose Save and continue, Save and add new, Print form, or Cancel.\n\nUse the matching Learning Center tutorials for step-by-step walkthroughs of each program.",
  },
  {
    id: "kb-18",
    title: "Consolidated Performance Contract Assessment",
    excerpt: "Load national consolidated performance contract results by region.",
    category: "Performance",
    tags: ["consolidated", "performance", "contract", "national"],
    type: "guide",
    body: "This workflow is done at national level:\n\na. Select the country of choice.\nb. On the top menu, click Consolidated Performance Contract.\nc. Select the year and region.\nd. Click Load Consolidated to view the consolidated assessment.",
  },
];

export const TUTORIALS: Tutorial[] = [
  {
    id: "tut-1",
    title: "How to log in to DDDP Frontend",
    summary: "Step-by-step sign-in for first-time users.",
    hasVideo: true,
    downloadable: true,
    videoUrl: DEMO_VIDEO,
    videoDuration: "1:30",
    steps: [
      "Open a supported browser (Chrome, Firefox, or Edge).",
      "Go to www.dddp.gov.gh (or your organisation’s DDDP Frontend URL).",
      "Enter your username and password, then click Sign In.",
      "Complete MFA if prompted, then land on the Dashboard.",
    ],
  },
  {
    id: "tut-2",
    title: "How to export a district report",
    summary: "Download PDF and spreadsheet exports from the frontend.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "Navigate to Reports in the frontend menu.",
      "Filter by district and reporting period.",
      "Click Export and choose PDF or Excel.",
      "Save the file to your device.",
    ],
  },
  {
    id: "tut-3",
    title: "How to submit a help desk ticket",
    summary: "Create and track support requests from this Help Desk.",
    hasVideo: true,
    downloadable: false,
    videoUrl: DEMO_VIDEO,
    videoDuration: "2:15",
    steps: [
      "Go to Help Desk → Tickets.",
      "Fill in subject, category, and description.",
      "Set priority and submit.",
      "Track status on the same page.",
    ],
  },
  {
    id: "tut-4",
    title: "How to search the knowledge base",
    summary: "Find articles, FAQs, and manuals quickly.",
    hasVideo: false,
    downloadable: false,
    steps: [
      "Open Knowledge Base from the sidebar.",
      "Type keywords in the search box.",
      "Filter by category or tag.",
      "Open an article to read the full guide.",
    ],
  },
  {
    id: "tut-5",
    title: "How to reset a forgotten password",
    summary: "Recover your DDDP account via email.",
    hasVideo: true,
    downloadable: true,
    videoUrl: DEMO_VIDEO,
    videoDuration: "1:45",
    steps: [
      "Open the DDDP login page at www.dddp.gov.gh.",
      "Click Forgot Password.",
      "Enter your Username and click Recover.",
      "Open the recovery link from your email.",
      "Enter and confirm a new password, then click Restore.",
    ],
  },
  {
    id: "tut-6",
    title: "How to complete Performance Setup",
    summary: "Select year, quarter, and indicators for a region.",
    hasVideo: true,
    downloadable: true,
    videoUrl: DEMO_VIDEO,
    videoDuration: "2:00",
    steps: [
      "Select a Region from the left side menu.",
      "Click Performance Setup on the top menu.",
      "Choose Year and Quarter.",
      "Scroll down and select one or more Indicators.",
      "Click Save Performance Setup.",
    ],
  },
  {
    id: "tut-7",
    title: "How to set up RCC monitoring indicators",
    summary: "Add indicators in RCC Indicator Setup mode.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "Click Setup Mode below the left menu pane.",
      "Open RCC Indicator Setup.",
      "Click +Add Indicator at the top right.",
      "Create the indicator and save.",
    ],
  },
  {
    id: "tut-8",
    title: "How to run an RCC monitoring assessment",
    summary: "Load district and consolidated regional assessments.",
    hasVideo: true,
    downloadable: true,
    videoUrl: DEMO_VIDEO,
    videoDuration: "3:00",
    steps: [
      "Select a Region and complete Performance Setup for Year/Quarter and indicators.",
      "Open the district page → Performance Monitoring tab.",
      "Select Year and Quarter, then click Load Assessment.",
      "For regional roll-up, open Consolidated Monitoring, select Year and Target Quarter, then Load Assessment.",
    ],
  },
  {
    id: "tut-9",
    title: "How to create an RCC Annual Progress Report",
    summary: "Start the progress report and save executive summary fields.",
    hasVideo: true,
    downloadable: true,
    videoUrl: DEMO_VIDEO,
    videoDuration: "2:40",
    steps: [
      "Select a Region from the left menu.",
      "Click RCC Progress Report on the top menu.",
      "Select Year and Period to populate tables.",
      "Click Start RCC Progress Report.",
      "Enter Executive Summary and General Information, then save both.",
    ],
  },
  {
    id: "tut-10",
    title: "How to complete a Performance Contract assessment",
    summary: "Load OHLGS records and complete regional or district contracts.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "Select a region (or district) from the side menu.",
      "Open Performance Contract Regional (or the district equivalent).",
      "Select Year and click Load Assessment.",
      "Review the OHLGS assessment record.",
      "Click Complete Assessment when finished.",
    ],
  },
  {
    id: "tut-11",
    title: "How to run Performance Monitoring",
    summary: "Start assessment, save indicators, and write the summary.",
    hasVideo: true,
    downloadable: true,
    videoUrl: DEMO_VIDEO,
    videoDuration: "3:10",
    steps: [
      "Select a Region, then open the district Performance Monitoring tab.",
      "Click Start Assessment to populate district data.",
      "Click Save Indicator.",
      "In Assessment Summary, record strengths, weaknesses, and technical backstopping needs.",
      "Save Assessment Summary, then click Complete Assessment.",
    ],
  },
  {
    id: "tut-12",
    title: "How to find and register a Tracker",
    summary: "Search trackers and register a new record.",
    hasVideo: true,
    downloadable: true,
    videoUrl: DEMO_VIDEO,
    videoDuration: "2:20",
    steps: [
      "Select a Region from the left menu.",
      "Click Trackers on the top menu.",
      "Use the search box to identify available trackers.",
      "Click Register, fill in the form, then Save and Continue or Save and Add New.",
    ],
  },
  {
    id: "tut-13",
    title: "How to bulk load tracker records",
    summary: "Download the template and upload multiple tracker rows.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "Select a District from the left side menu.",
      "Open Trackers on the top menu.",
      "Click Bulk load.",
      "Download Template and populate the required columns.",
      "Upload the completed file to import records.",
    ],
  },
  {
    id: "tut-14",
    title: "How to add a Timeline event on a Tracker",
    summary: "Create a new event on a registered tracker record.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "Select a District and open Trackers.",
      "Search for and select a tracker, then open a registered record.",
      "Click Timeline.",
      "Click New Event, fill in the details, and click Continue.",
    ],
  },
  {
    id: "tut-15",
    title: "How to add a Tracker relationship",
    summary: "Link related records under Relationship.",
    hasVideo: false,
    downloadable: false,
    steps: [
      "Open Trackers for a District and select a registered record.",
      "Click Relationship.",
      "Click Add Relationship and choose the relationship type.",
      "Fill in the details and click Register Relationship.",
    ],
  },
  {
    id: "tut-16",
    title: "How to view the APR Dashboard",
    summary: "Open the national Annual Progress Report summary for Ghana.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "Select Ghana (national level).",
      "Click APR Dashboard on the top menu.",
      "Select a Year.",
      "Scroll to review the national summary report.",
    ],
  },
  {
    id: "tut-17",
    title: "How to view the DPAT Dashboard",
    summary: "Open the national DPAT summary report for Ghana.",
    hasVideo: true,
    downloadable: true,
    videoUrl: DEMO_VIDEO,
    videoDuration: "1:50",
    steps: [
      "Select Ghana (national level).",
      "Click DPAT Dashboard on the top menu.",
      "Select a Year.",
      "Scroll down to view the DPAT summary report.",
    ],
  },
  {
    id: "tut-18",
    title: "How to load Consolidated Performance Contract",
    summary: "View consolidated contract assessment by year and region.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "Select the country at national level.",
      "Open Consolidated Performance Contract from the top menu.",
      "Select Year and Region.",
      "Click Load Consolidated.",
    ],
  },
  {
    id: "tut-19",
    title: "How to register a Meeting in Tracker Capture",
    summary: "Capture a Meeting program registration.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "On Tracker Capture, open the program dropdown.",
      "Select Meeting Program.",
      "Click Register and complete the form.",
      "Choose Save and continue, Save and add new, Print form, or Cancel.",
    ],
  },
  {
    id: "tut-20",
    title: "How to register an Annual Action Plan",
    summary: "Register an AAP record in Tracker Capture.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "Open the Tracker Capture dropdown and select Annual Action Plan.",
      "Click Register.",
      "Fill in the required information.",
      "Save and continue, or Save and add new for another plan.",
    ],
  },
  {
    id: "tut-21",
    title: "How to register Bill and Boundary Dispute Trackers",
    summary: "Register Bill Tracker or Boundary Dispute Tracker programs.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "Open Tracker Capture and select Bill Tracker or Boundary Dispute Tracker.",
      "Click Register.",
      "Complete the form fields.",
      "Save and continue or Save and add new.",
    ],
  },
  {
    id: "tut-22",
    title: "How to register Capacity, Community, and System Trackers",
    summary: "Capacity Building Needs, Community Profile, and Computerized System.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "From Tracker Capture, select Capacity Building Needs, Community Profile, or Computerized System Tracker.",
      "Click Register and fill in the form.",
      "Use Save and continue to open the tracker page, or Save and add new for another entry.",
      "Print form if you need a paper copy, or Cancel to abort.",
    ],
  },
  {
    id: "tut-23",
    title: "How to register Decisions and Complaints Tracker",
    summary: "Capture decisions and complaints records in Tracker Capture.",
    hasVideo: false,
    downloadable: true,
    steps: [
      "Open the Tracker Capture dropdown.",
      "Select Decisions and Complaints Tracker.",
      "Click Register and enter the required details.",
      "Save and continue, Save and add new, Print form, or Cancel.",
    ],
  },
];

export const TICKET_CATEGORIES = [
  "Account & access",
  "Data & reports",
  "Technical issue",
  "Training request",
  "Other",
] as const;
